### ISSUE TITLE
Eliminar mensajes de confirmación innecesarios

### ISSUE THREAD

**Issue by BrayanYinLin** [BrayanYinLin/hotel-management-app#21]
## Explicación
Los mensajes de confirmación incrementan la fricción en el flujo de trabajo, deben ser eliminados para reducir la cantidad clics requeridos para realizar una operación

>[!WARNING]
>¡Por favor!, no olvidar crear una rama y hacer una PR para realizar estos cambios

![image](https://github.com/user-attachments/assets/2098ccca-2102-4f59-86fa-0e1067ba1f42)

**Comment by vincx0** [comment]
se quito el dialog para que no pueda aparecer la confirmación y pasar a editar directamente
