### ISSUE TITLE
Los formularios de habitaciones y tipo habitaciones no están bien acomodados

### ISSUE THREAD

**Issue by BrayanYinLin** [BrayanYinLin/hotel-management-app#23]
>[!IMPORTANT]
>El formulario de habitaciones y huespedes esta desacomodado y debe corregirse entes del entregable del 4 de Diciembre, deshabilitar la opción del resize

![image](https://github.com/user-attachments/assets/cd213dc0-3dff-4511-be2f-b381a30fa1bb)

![image](https://github.com/user-attachments/assets/b54361c6-3c81-472a-8a18-fc4195b1cb87)

**Comment by vincx0** [comment]
se cambio de sizable a fixedSingle para que no se pueda agrandar mas, se elimino el botón cerrar porque no es necesario y se ajusto anchor de la cantidad y  del botón buscar
